[placeholders]
github_org = { type = "string", prompt = "Github username/organization?", default = "BVE-Reborn" }
copyright = { type = "string", prompt = "Name on copyright? [used as: 'Copyright 2021 <answer>']", default = "the BVE-Reborn developers" }
wasm = { type = "bool", prompt = "Support WASM?", default = true }
msrv = { type = "string", prompt = "Minimum Supported Rust Version? [X.YY or None]", regex = "(\\d+\\.\\d+)|None", default = "None" }
ci_timeout = { type = "string", prompt = "How long should CI wait before timing out?", default = "30" }
description = { type = "string", prompt = "Project description?", default = "" }
