[placeholders]
wasm = { type = "bool", prompt = "Support WASM?", default = "true" }
msrv = { type = "string", prompt = "What Minimum Supported Rust Version (MSRV)?", regex = "\\d+\\.\\d+"}
ci_timeout = { type = "string", prompt = "How long should CI wait before timing out?", default = "30" }

