[package]
name = "{{project-name}}"
version = "0.1.0"
authors = ["{{authors}}"]
edition = "2018"
description = ".."
readme = "README.md"
repository = "https://github.com/BVE-Reborn/{{project-name}}"
license = "MIT OR Apache-2.0 OR Zlib"
keywords = []
categories = []
