name: Build

on:
  push:
  pull_request:

jobs:
  build:
    timeout-minutes: {{ ci_timeout }}

    strategy:
      matrix:
        include:
          {% if wasm %}
          # wasm stable
          - name: 'stable wasm'
            os: 'ubuntu-latest'
            target: 'wasm32-unknown-unknown'
            rust_version: 'stable'
          {% endif %}

          # native stable
          - name: 'stable linux'
            os: 'ubuntu-latest'
            target: 'x86_64-unknown-linux-gnu'
            rust_version: 'stable'
          - name: 'stable mac'
            os: 'macos-latest'
            target: 'x86_64-apple-darwin'
            rust_version: 'stable'
          - name: 'stable windows'
            os: 'windows-latest'
            target: 'x86_64-pc-windows-msvc'
            rust_version: 'stable'

          {% if msrv != "None" %}
          {% if wasm %}
          # wasm MSRV
          - name: '{{msrv}} wasm'
            os: 'ubuntu-latest'
            target: 'wasm32-unknown-unknown'
            rust_version: '{{msrv}}'
          {% endif %}

          # native MSRV
          - name: '{{msrv}} linux'
            os: 'ubuntu-latest'
            target: 'x86_64-unknown-linux-gnu'
            rust_version: '{{msrv}}'
          - name: '{{msrv}} mac'
            os: 'macos-latest'
            target: 'x86_64-apple-darwin'
            rust_version: '{{msrv}}'
          - name: '{{msrv}} windows'
            os: 'windows-latest'
            target: 'x86_64-pc-windows-msvc'
            rust_version: '{{msrv}}'
          {% endif %}
      fail-fast: false
    {% raw %}
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.name }}

    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: load cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ matrix.os }}-${{ matrix.target }}-${{ matrix.rust_version }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ matrix.os }}-${{ matrix.target }}-${{ matrix.rust_version }}-cargo-

      - name: install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust_version }}
          target: ${{ matrix.target }}
          profile: minimal
          components: clippy
          default: true
          
      - name: check
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --target ${{ matrix.target }} -- -D warnings 
          
      - name: build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target ${{ matrix.target }}
          
      - name: test
        uses: actions-rs/cargo@v1
        with:
          command: test
        if: ${{ matrix.name != 'wasm' }}
          
      - name: doc
        uses: actions-rs/cargo@v1
        env:
          RUSTDOCFLAGS: -D warnings
        with:
          command: doc
          args: --no-deps --target ${{ matrix.target }}

  cargo-fmt:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          components: rustfmt
          default: true

      - name: check format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check

  cargo-deny:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: check denies
        uses: EmbarkStudios/cargo-deny-action@v1
        with:
          log-level: warn
          command: check
          arguments: --all-features

  publish:
    runs-on: ubuntu-latest
    
    needs: ['build', 'cargo-fmt', 'cargo-deny']
    if: ${{ startsWith(github.ref, "refs/tags/v") }}

    steps:
      - name: checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          default: true
      
      - name: install cargo-release
        run: |
          cargo install cargo-release

      - name: release to crates.io
        run: |
          git config user.name "releasebot"
          git config user.email "actions@users.noreply.github.com"

          cargo login ${{ secrets.CRATES_TOKEN }}
          cargo release --skip-publish --no-confirm $( echo '${{ github.ref }}' | sed 's?refs/tags/v??' )
      
      - name: generate release notes
        id: notes
        run: |
          NOTES=$(grep -zoP '## v\d+.\d+.\d+(\n|.)*(?=## )' CHANGELOG.md | sed '1,4d')
          echo "::set-output name=notes::$NOTES"

      - name: release to github
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{ steps.notes.outputs.notes }}
          draft: false
          prerelease: false

{% endraw %}
